<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EGT0M14" failures="1" tests="3" name="Submit Order Test" time="49.355" errors="0" timestamp="2024-02-16T21:36:03 IST">
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="submitorder" time="13.698"/>
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="submitorder" time="13.262"/>
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="validateOrder" time="0.005">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder.validateOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Ria@1991, product=IPHONE 13 PRO, email=achokroborty@gmail.com}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder.validateOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Ria@1991, product=IPHONE 13 PRO, email=achokroborty@gmail.com}]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- validateOrder -->
</testsuite> <!-- Submit Order Test -->
